import customtkinter
from PIL import Image, ImageTk

app = customtkinter.CTk()
app.title("Ludo")
app.geometry("705x705")
app.resizable(False, False)
app.grid_columnconfigure(15, weight=1)
app.grid_rowconfigure(15, weight=1)
app.pack_propagate(False)

image = Image.open("star.png")
resized_image = image.resize((34, 34))
rimage = ImageTk.PhotoImage(resized_image)

b1 = customtkinter.CTkFrame(app, fg_color="#04d423", corner_radius=2, height=279, width=279)
b1.grid(row=0, column=0, columnspan=6, rowspan=6, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=6, column=0, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=7, column=0, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=8, column=0, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkFrame(app, fg_color="#eef205", corner_radius=2,height=279, width=279)
b1.grid(row=9, column=0, pady=(1, 1), padx=(1, 1), columnspan=6, rowspan=6)

b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#04d423", corner_radius=2,height=45, width=45)
b1.grid(row=6, column=1, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#04d423", corner_radius=2,height=45, width=45)
b1.grid(row=7, column=1, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=8, column=1, pady=(1, 1), padx=(1, 1))

b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=6, column=2, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#04d423", corner_radius=2,height=45, width=45)
b1.grid(row=7, column=2, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), image=rimage, fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=8, column=2, pady=(1, 1), padx=(1, 1))

b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=6, column=3, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#04d423", corner_radius=2,height=45, width=45)
b1.grid(row=7, column=3, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=8, column=3, pady=(1, 1), padx=(1, 1))

b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=6, column=4, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#04d423", corner_radius=2,height=45, width=45)
b1.grid(row=7, column=4, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=8, column=4, pady=(1, 1), padx=(1, 1))

b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=6, column=5, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#04d423", corner_radius=2,height=45, width=45)
b1.grid(row=7, column=5, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=8, column=5, pady=(1, 1), padx=(1, 1))

b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=0, column=6, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=1, column=6, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60),  image=rimage, fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=2, column=6, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=3, column=6, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=4, column=6, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=5, column=6, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#8d02e3", corner_radius=2,height=137, width=137)
b1.grid(row=6, column=6, pady=(1, 1), padx=(1, 1), columnspan=3, rowspan=3)
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=9, column=6, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=10, column=6, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=11, column=6, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=12, column=6, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#eef205", corner_radius=2,height=45, width=45)
b1.grid(row=13, column=6, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=14, column=6, pady=(1, 1), padx=(1, 1))

b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=0, column=7, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#f20511", corner_radius=2,height=45, width=45)
b1.grid(row=1, column=7, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#f20511", corner_radius=2,height=45, width=45)
b1.grid(row=2, column=7, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#f20511", corner_radius=2,height=45, width=45)
b1.grid(row=3, column=7, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#f20511", corner_radius=2,height=45, width=45)
b1.grid(row=4, column=7, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#f20511", corner_radius=2,height=45, width=45)
b1.grid(row=5, column=7, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#eef205", corner_radius=2,height=45, width=45)
b1.grid(row=9, column=7, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#eef205", corner_radius=2,height=45, width=45)
b1.grid(row=10, column=7, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#eef205", corner_radius=2,height=45, width=45)
b1.grid(row=11, column=7, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#eef205", corner_radius=2,height=45, width=45)
b1.grid(row=12, column=7, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#eef205", corner_radius=2,height=45, width=45)
b1.grid(row=13, column=7, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=14, column=7, pady=(1, 1), padx=(1, 1))

b1 = customtkinter.CTkFrame(app, fg_color="#f20511", corner_radius=2,height=279, width=279)
b1.grid(row=0, column=9, pady=(1, 1), padx=(1, 1), columnspan=6, rowspan=6)

b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=6, column=9, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#0255ed", corner_radius=2,height=45, width=45)
b1.grid(row=7, column=9, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=8, column=9, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkFrame(app, fg_color="#0255ed", corner_radius=2,height=279, width=279)
b1.grid(row=9, column=9, pady=(1, 1), padx=(1, 1), columnspan=6, rowspan=6)

b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=0, column=8, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#f20511", corner_radius=2,height=45, width=45)
b1.grid(row=1, column=8, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=2, column=8, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=3, column=8, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=4, column=8, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=5, column=8, pady=(1, 1), padx=(1, 1))

b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=9, column=8, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=10, column=8, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=11, column=8, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), image=rimage, fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=12, column=8, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=13, column=8, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=14, column=8, pady=(1, 1), padx=(1, 1))

b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=6, column=10, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#0255ed", corner_radius=2,height=45, width=45)
b1.grid(row=7, column=10, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=8, column=10, pady=(1, 1), padx=(1, 1))

b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=6, column=11, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#0255ed", corner_radius=2,height=45, width=45)
b1.grid(row=7, column=11, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=8, column=11, pady=(1, 1), padx=(1, 1))

b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), image=rimage, fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=6, column=12, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#0255ed", corner_radius=2,height=45, width=45)
b1.grid(row=7, column=12, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=8, column=12, pady=(1, 1), padx=(1, 1))

b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=6, column=13, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#0255ed", corner_radius=2,height=45, width=45)
b1.grid(row=7, column=13, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#0255ed", corner_radius=2,height=45, width=45)
b1.grid(row=8, column=13, pady=(1, 1), padx=(1, 1))

b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=6, column=14, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=7, column=14, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=8, column=14, pady=(1, 1), padx=(1, 1))

app.mainloop()
