
import customtkinter

app = customtkinter.CTk()
app.title("Ludo")
app.geometry("705x705")
app.resizable(False, False)
app.grid_columnconfigure(15, weight=1)
app.grid_rowconfigure(15, weight=1)
app.pack_propagate(False)

b1 = customtkinter.CTkFrame(app, fg_color="#04d423", corner_radius=2, height=279, width=279)
b1.grid(row=0, column=0, columnspan=6, rowspan=6, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkFrame(app, text="", font=("Helvetica", 60), fg_color="#04d423", corner_radius=2,height=228, width=45)
# b1.grid(row=1, column=0, rowspan=5, pady=(0, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=2, column=0, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=3, column=0, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=4, column=0, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=5, column=0, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=6, column=0, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=7, column=0, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=8, column=0, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkFrame(app, fg_color="#eef205", corner_radius=2,height=279, width=279)
b1.grid(row=9, column=0, pady=(1, 1), padx=(1, 1), columnspan=6, rowspan=6)
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=10, column=0, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=11, column=0, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=12, column=0, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=13, column=0, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=14, column=0, pady=(1, 1), padx=(1, 1))


# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=0, column=1, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=1, column=1, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=2, column=1, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=3, column=1, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=4, column=1, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=5, column=1, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=6, column=1, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=7, column=1, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=8, column=1, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=9, column=1, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=10, column=1, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=11, column=1, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=12, column=1, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=13, column=1, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=14, column=1, pady=(1, 1), padx=(1, 1))


# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=0, column=2, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=1, column=2, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=2, column=2, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=3, column=2, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=4, column=2, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=5, column=2, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=6, column=2, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=7, column=2, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=8, column=2, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=9, column=2, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=10, column=2, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=11, column=2, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=12, column=2, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=13, column=2, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=14, column=2, pady=(1, 1), padx=(1, 1))

# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=0, column=3, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=1, column=3, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=2, column=3, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=3, column=3, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=4, column=3, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=5, column=3, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=6, column=3, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=7, column=3, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=8, column=3, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=9, column=3, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=10, column=3, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=11, column=3, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=12, column=3, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=13, column=3, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=14, column=3, pady=(1, 1), padx=(1, 1))


# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=0, column=2, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=1, column=4, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=2, column=4, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=3, column=4, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=4, column=4, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=5, column=4, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=6, column=4, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=7, column=4, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=8, column=4, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=9, column=4, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=10, column=4, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=11, column=4, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=12, column=4, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=13, column=4, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=14, column=4, pady=(1, 1), padx=(1, 1))


# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=0, column=2, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=1, column=5, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=2, column=5, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=3, column=5, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=4, column=5, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=5, column=5, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=6, column=5, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=7, column=5, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=8, column=5, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=9, column=5, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=10, column=5, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=11, column=5, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=12, column=5, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=13, column=5, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=14, column=5, pady=(1, 1), padx=(1, 1))


b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=0, column=6, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=1, column=6, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=2, column=6, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=3, column=6, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=4, column=6, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=5, column=6, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=6, column=6, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=7, column=6, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=8, column=6, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=9, column=6, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=10, column=6, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=11, column=6, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=12, column=6, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=13, column=6, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=14, column=6, pady=(1, 1), padx=(1, 1))


b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=0, column=7, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=1, column=7, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=2, column=7, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=3, column=7, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=4, column=7, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=5, column=7, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=6, column=7, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=7, column=7, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=8, column=7, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=9, column=7, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=10, column=7, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=11, column=7, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=12, column=7, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=13, column=7, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=14, column=7, pady=(1, 1), padx=(1, 1))

b1 = customtkinter.CTkFrame(app, fg_color="#f20511", corner_radius=2,height=279, width=279)
b1.grid(row=0, column=9, pady=(1, 1), padx=(1, 1), columnspan=6, rowspan=6)
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=1, column=9, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=2, column=9, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=3, column=9, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=4, column=9, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=5, column=9, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=6, column=9, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=7, column=9, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=8, column=9, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkFrame(app, fg_color="#0255ed", corner_radius=2,height=279, width=279)
b1.grid(row=9, column=9, pady=(1, 1), padx=(1, 1), columnspan=6, rowspan=6)
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=10, column=9, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=11, column=9, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=12, column=9, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=13, column=9, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=14, column=9, pady=(1, 1), padx=(1, 1))

b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=0, column=8, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=1, column=8, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=2, column=8, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=3, column=8, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=4, column=8, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=5, column=8, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=6, column=8, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=7, column=8, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=8, column=8, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=9, column=8, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=10, column=8, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=11, column=8, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=12, column=8, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=13, column=8, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=14, column=8, pady=(1, 1), padx=(1, 1))

# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=0, column=10, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=1, column=10, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=2, column=10, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=3, column=10, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=4, column=10, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=5, column=10, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=6, column=10, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=7, column=10, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=8, column=10, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=9, column=10, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=10, column=10, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=11, column=10, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=12, column=10, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=13, column=10, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=14, column=10, pady=(1, 1), padx=(1, 1))

# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=0, column=11, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=1, column=11, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=2, column=11, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=3, column=11, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=4, column=11, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=5, column=11, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=6, column=11, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=7, column=11, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=8, column=11, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=9, column=11, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=10, column=11, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=11, column=11, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=12, column=11, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=13, column=11, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=14, column=11, pady=(1, 1), padx=(1, 1))

# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=0, column=12, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=1, column=12, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=2, column=12, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=3, column=12, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=4, column=12, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=5, column=12, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=6, column=12, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=7, column=12, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=8, column=12, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=9, column=12, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=10, column=12, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=11, column=12, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=12, column=12, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=13, column=12, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=14, column=12, pady=(1, 1), padx=(1, 1))

# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=0, column=13, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=1, column=13, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=2, column=13, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=3, column=13, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=4, column=13, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=5, column=13, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=6, column=13, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=7, column=13, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=8, column=13, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=9, column=13, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=10, column=13, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=11, column=13, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=12, column=13, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=13, column=13, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=14, column=13, pady=(1, 1), padx=(1, 1))

# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=0, column=14, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=1, column=14, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=2, column=14, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=3, column=14, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=4, column=14, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=5, column=14, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=6, column=14, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=7, column=14, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
b1.grid(row=8, column=14, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=9, column=14, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=10, column=14, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=11, column=14, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=12, column=14, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", corner_radius=2,height=45, width=45)
# b1.grid(row=13, column=14, pady=(1, 1), padx=(1, 1))
# b1 = customtkinter.CTkFrame(app, fg_color="#04d423", corner_radius=2, height=270, width=270)
# b1.grid(row=14, column=14, columnspan=6, rowspan=6, pady=(1, 1), padx=(1, 1), sticky="nw")

app.mainloop()
