import customtkinter

customtkinter.set_appearance_mode("dark")
customtkinter.set_default_color_theme("green")

app = customtkinter.CTk()
app.geometry("330x490")
app.title("Calculator")
app.resizable(False, False)

bomb_label = customtkinter.CTkButton(app, text="C", font=("Helvetica", 17), height=35, width=35)
bomb_label.grid(row=1, column=0, pady=(0, 8), padx=(2,2))
bomb_label = customtkinter.CTkButton(app, text="()", font=("Helvetica", 17), height=35, width=35)
bomb_label.grid(row=1, column=1, pady=(0, 8), padx=(2,2))
bomb_label = customtkinter.CTkButton(app, text="<", font=("Helvetica", 17), height=88, width=35)
bomb_label.grid(row=1, column=2, pady=(0, 8), padx=(2,2), rowspan=3)
bomb_label = customtkinter.CTkButton(app, text="^", font=("Helvetica", 17), height=35, width=35)
bomb_label.grid(row=1, column=3, pady=(0, 8), padx=(2,2))
bomb_label = customtkinter.CTkButton(app, text=">", font=("Helvetica", 17), height=88, width=35)
bomb_label.grid(row=1, column=4, pady=(0, 8), padx=(2,2), rowspan=3)
bomb_label = customtkinter.CTkButton(app, text="/", font=("Helvetica", 17), height=35, width=35)
bomb_label.grid(row=1, column=5, pady=(0, 8), padx=(2,2))
bomb_label = customtkinter.CTkButton(app, text="/", font=("Helvetica", 17), height=35, width=35)
bomb_label.grid(row=1, column=6, pady=(0, 8), padx=(2,2))

bomb_label = customtkinter.CTkButton(app, text="C", font=("Helvetica", 17), height=35, width=35)
bomb_label.grid(row=3, column=0, pady=(0, 8), padx=(2,2))
bomb_label = customtkinter.CTkButton(app, text="()", font=("Helvetica", 17), height=35, width=35)
bomb_label.grid(row=3, column=1, pady=(0, 8), padx=(2,2))
bomb_label = customtkinter.CTkButton(app, text="", font=("Helvetica", 17), height=35, width=35)
bomb_label.grid(row=3, column=3, pady=(0, 8), padx=(2,2))
bomb_label = customtkinter.CTkButton(app, text="/", font=("Helvetica", 17), height=35, width=35)
bomb_label.grid(row=3, column=5, pady=(0, 8), padx=(2,2))
bomb_label = customtkinter.CTkButton(app, text="/", font=("Helvetica", 17), height=35, width=35)
bomb_label.grid(row=3, column=6, pady=(0, 8), padx=(2,2))

bomb_label = customtkinter.CTkButton(app, text="C", font=("Helvetica", 17), height=35, width=35)
bomb_label.grid(row=4, column=0, pady=(0, 8), padx=(2,2))
bomb_label = customtkinter.CTkButton(app, text="()", font=("Helvetica", 17), height=35, width=35)
bomb_label.grid(row=4, column=1, pady=(0, 8), padx=(2,2))
bomb_label = customtkinter.CTkButton(app, text="%", font=("Helvetica", 17), height=35, width=35)
bomb_label.grid(row=4, column=2, pady=(0, 8), padx=(2,2))
bomb_label = customtkinter.CTkButton(app, text="/", font=("Helvetica", 17), height=35, width=35)
bomb_label.grid(row=4, column=3, pady=(0, 8), padx=(2,2))
bomb_label = customtkinter.CTkButton(app, text="/", font=("Helvetica", 17), height=35, width=35)
bomb_label.grid(row=4, column=4, pady=(0, 8), padx=(2,2))
bomb_label = customtkinter.CTkButton(app, text="/", font=("Helvetica", 17), height=35, width=35)
bomb_label.grid(row=4, column=5, pady=(0, 8), padx=(2,2))
bomb_label = customtkinter.CTkButton(app, text="/", font=("Helvetica", 17), height=35, width=35)
bomb_label.grid(row=4, column=6, pady=(0, 8), padx=(2,2))

bomb_label = customtkinter.CTkButton(app, text="C", font=("Helvetica", 17), height=35, width=35)
bomb_label.grid(row=5, column=0, pady=(0, 8), padx=(2,2))
bomb_label = customtkinter.CTkButton(app, text="()", font=("Helvetica", 17), height=35, width=35)
bomb_label.grid(row=5, column=1, pady=(0, 8), padx=(2,2))
bomb_label = customtkinter.CTkButton(app, text="%", font=("Helvetica", 17), height=35, width=35)
bomb_label.grid(row=5, column=2, pady=(0, 8), padx=(2,2))
bomb_label = customtkinter.CTkButton(app, text="/", font=("Helvetica", 17), height=35, width=35)
bomb_label.grid(row=5, column=3, pady=(0, 8), padx=(2,2))
bomb_label = customtkinter.CTkButton(app, text="/", font=("Helvetica", 17), height=35, width=35)
bomb_label.grid(row=5, column=4, pady=(0, 8), padx=(2,2))
bomb_label = customtkinter.CTkButton(app, text="/", font=("Helvetica", 17), height=35, width=35)
bomb_label.grid(row=5, column=5, pady=(0, 8), padx=(2,2))
bomb_label = customtkinter.CTkButton(app, text="/", font=("Helvetica", 17), height=35, width=35)
bomb_label.grid(row=5, column=6, pady=(0, 8), padx=(2,2))

bomb_label = customtkinter.CTkButton(app, text="C", font=("Helvetica", 17), height=35, width=35)
bomb_label.grid(row=6, column=0, pady=(0, 8), padx=(2,2))
bomb_label = customtkinter.CTkButton(app, text="()", font=("Helvetica", 17), height=35, width=35)
bomb_label.grid(row=6, column=1, pady=(0, 8), padx=(2,2))
bomb_label = customtkinter.CTkButton(app, text="%", font=("Helvetica", 17), height=35, width=35)
bomb_label.grid(row=6, column=2, pady=(0, 8), padx=(2,2))
bomb_label = customtkinter.CTkButton(app, text="/", font=("Helvetica", 17), height=35, width=35)
bomb_label.grid(row=6, column=3, pady=(0, 8), padx=(2,2))
bomb_label = customtkinter.CTkButton(app, text="/", font=("Helvetica", 17), height=35, width=35)
bomb_label.grid(row=6, column=4, pady=(0, 8), padx=(2,2))
bomb_label = customtkinter.CTkButton(app, text="/", font=("Helvetica", 17), height=35, width=35)
bomb_label.grid(row=6, column=5, pady=(0, 8), padx=(2,2))
bomb_label = customtkinter.CTkButton(app, text="/", font=("Helvetica", 17), height=35, width=35)
bomb_label.grid(row=6, column=6, pady=(0, 8), padx=(2,2))

bomb_label = customtkinter.CTkButton(app, text="1", font=("Helvetica", 17), height=35, width=80)
bomb_label.grid(row=7, column=0, pady=(0, 8), padx=(2,2), columnspan=2)
bomb_label = customtkinter.CTkButton(app, text="2", font=("Helvetica", 17), height=35, width=80)
bomb_label.grid(row=7, column=2, pady=(0, 8), padx=(2,2), columnspan=2)
bomb_label = customtkinter.CTkButton(app, text="3", font=("Helvetica", 17), height=35, width=80)
bomb_label.grid(row=7, column=4, pady=(0, 8), padx=(2,2), columnspan=2)
bomb_label = customtkinter.CTkButton(app, text="+", font=("Helvetica", 17), height=35, width=35)
bomb_label.grid(row=7, column=6, pady=(0, 8), padx=(2,2))

bomb_label = customtkinter.CTkButton(app, text="4", font=("Helvetica", 17), height=35, width=80)
bomb_label.grid(row=8, column=0, pady=(0, 8), padx=(2,2), columnspan=2)
bomb_label = customtkinter.CTkButton(app, text="2", font=("Helvetica", 17), height=35, width=80)
bomb_label.grid(row=8, column=2, pady=(0, 8), padx=(2,2), columnspan=2)
bomb_label = customtkinter.CTkButton(app, text="6", font=("Helvetica", 17), height=35, width=80)
bomb_label.grid(row=8, column=4, pady=(0, 8), padx=(2,2), columnspan=2)
bomb_label = customtkinter.CTkButton(app, text="-", font=("Helvetica", 17), height=35, width=35)
bomb_label.grid(row=8, column=6, pady=(0, 8), padx=(2,2))

bomb_label = customtkinter.CTkButton(app, text="7", font=("Helvetica", 17), height=35, width=80)
bomb_label.grid(row=9, column=0 , pady=(0, 8), padx=(2,2), columnspan=2)
bomb_label = customtkinter.CTkButton(app, text="8", font=("Helvetica", 17), height=35, width=80)
bomb_label.grid(row=9, column=2, pady=(0, 8), padx=(2,2), columnspan=2)
bomb_label = customtkinter.CTkButton(app, text="9", font=("Helvetica", 17), height=35, width=80)
bomb_label.grid(row=9, column=4, pady=(0, 8), padx=(2,2), columnspan=2)
bomb_label = customtkinter.CTkButton(app, text="x", font=("Helvetica", 17), height=35, width=35)
bomb_label.grid(row=9, column=6, pady=(0, 8), padx=(2,2))

bomb_label = customtkinter.CTkButton(app, text="+/-", font=("Helvetica", 17), height=35, width=80)
bomb_label.grid(row=10, column=0 , pady=(0, 8), padx=(2,2), columnspan=2)
bomb_label = customtkinter.CTkButton(app, text="0", font=("Helvetica", 17), height=35, width=80)
bomb_label.grid(row=10, column=2, pady=(0, 8), padx=(2,2), columnspan=2)
bomb_label = customtkinter.CTkButton(app, text=".", font=("Helvetica", 17), height=35, width=80)
bomb_label.grid(row=10, column=4, pady=(0, 8), padx=(2,2), columnspan=2)
bomb_label = customtkinter.CTkButton(app, text="=", font=("Helvetica", 17), height=35, width=35)
bomb_label.grid(row=10, column=6, pady=(0, 8), padx=(2,2))

output = customtkinter.CTkLabel(app, text="", fg_color="#131313", width=300, height=61, corner_radius=7)
output.grid(row=0, column=0, columnspan=7, padx=(10, 10), pady=15)
app.mainloop()
