import math

import customtkinter

customtkinter.set_appearance_mode("light")

class App(customtkinter.CTk):
    def __init__(self):
        super().__init__()

        self.title("Time Table")
        self.geometry("730x410")
        self.resizable(False, False)
        self.rowconfigure(9, weight=1)
        self.columnconfigure(9, weight=1)

        self.main_frame = customtkinter.CTkFrame(self, fg_color="white")
        self.main_frame.pack(fill="both", expand=True)
        self.main_frame2 = customtkinter.CTkFrame(self.main_frame, fg_color="white", width=700)
        self.main_frame2.grid(row=1, padx=0, pady=0, columnspan=9)
        self.Tabview = customtkinter.CTkTabview(self.main_frame, height=300, fg_color="white", width=700)
        self.Tabview.grid(row=2, padx=0, pady=0, columnspan=9)
        self.Tabview.add("Day")
        self.Tabview.add("Night")
        self.Tabview.tab("Day").grid_columnconfigure(25)
        self.Tabview.tab("Night").grid_columnconfigure(25)
        self.Task = customtkinter.CTkLabel(self.main_frame, text="Task", font=("Helvetica", 16))
        self.Task.grid(row=0, column=0, padx=(5, 0), pady=(10, 10))
        self.Task1 = customtkinter.CTkEntry(self.main_frame, width=200)
        self.Task1.grid(row=0, column=1, padx=(0, 5), pady=(10, 10))
        self.welcome = customtkinter.CTkLabel(self.main_frame, text="From", font=("Helvetica", 16))
        self.welcome.grid(row=0, column=2, padx=(0, 0))
        self.From = customtkinter.CTkEntry(self.main_frame, width=100)
        self.From.grid(row=0, column=3, padx=(0, 5), pady=(10, 10))
        self.welcome = customtkinter.CTkLabel(self.main_frame, text="To", font=("Helvetica", 16))
        self.welcome.grid(row=0, column=4, padx=(0, 0))
        self.To = customtkinter.CTkEntry(self.main_frame, width=100)
        self.To.grid(row=0, column=5, padx=(0, 5), pady=(10, 10))
        self.welcome = customtkinter.CTkButton(self.main_frame, text="Add", command=self.add, width=40, font=("Helvetica", 16))
        self.welcome.grid(row=0, column=6, padx=(0, 5))
        self.welcome = customtkinter.CTkButton(self.main_frame, text="Delete", width=40, font=("Helvetica", 16))
        self.welcome.grid(row=0, column=7, padx=(0, 0))
        self.radio_button_1 = customtkinter.CTkCheckBox(self.main_frame2, text="Mon")
        self.radio_button_1.grid(row=1, column=0, pady=10, padx=(5, 2), sticky="nw")
        self.radio_button_1 = customtkinter.CTkCheckBox(self.main_frame2, text="Tue")
        self.radio_button_1.grid(row=1, column=1, pady=10, padx=(0, 2), sticky="nw")
        self.radio_button_1 = customtkinter.CTkCheckBox(self.main_frame2, text="Wed")
        self.radio_button_1.grid(row=1, column=2, pady=10, padx=(0, 2), sticky="nw")
        self.radio_button_1 = customtkinter.CTkCheckBox(self.main_frame2, text="Thu")
        self.radio_button_1.grid(row=1, column=3, pady=10, padx=(0, 2), sticky="nw")
        self.radio_button_1 = customtkinter.CTkCheckBox(self.main_frame2, text="Fri")
        self.radio_button_1.grid(row=1, column=4, pady=10, padx=(0, 2), sticky="nw")
        self.radio_button_1 = customtkinter.CTkCheckBox(self.main_frame2, text="Sat")
        self.radio_button_1.grid(row=1, column=5, pady=10, padx=(0, 2), sticky="nw")
        self.radio_button_1 = customtkinter.CTkCheckBox(self.main_frame2, text="Sun")
        self.radio_button_1.grid(row=1, column=6, pady=10, padx=(0, 2), sticky="nw")

        self.welcome = customtkinter.CTkLabel(self.Tabview.tab("Day"), text="1:00PM", font=("Helvetica", 13))
        self.welcome.grid(row=0, column=1, padx=(10, 12))
        self.welcome = customtkinter.CTkLabel(self.Tabview.tab("Day"), text="2:00PM", font=("Helvetica", 13))
        self.welcome.grid(row=0, column=2, padx=(0, 12))
        self.welcome = customtkinter.CTkLabel(self.Tabview.tab("Day"), text="3:00PM", font=("Helvetica", 13))
        self.welcome.grid(row=0, column=3, padx=(0, 12))
        self.welcome = customtkinter.CTkLabel(self.Tabview.tab("Day"), text="4:00PM", font=("Helvetica", 13))
        self.welcome.grid(row=0, column=4, padx=(0, 12))
        self.welcome = customtkinter.CTkLabel(self.Tabview.tab("Day"), text="5:00PM", font=("Helvetica", 13))
        self.welcome.grid(row=0, column=5, padx=(0, 12))
        self.welcome = customtkinter.CTkLabel(self.Tabview.tab("Day"), text="6:00PM", font=("Helvetica", 13))
        self.welcome.grid(row=0, column=6, padx=(0, 12))
        self.welcome = customtkinter.CTkLabel(self.Tabview.tab("Day"), text="7:00PM", font=("Helvetica", 13))
        self.welcome.grid(row=0, column=7, padx=(0, 12))
        self.welcome = customtkinter.CTkLabel(self.Tabview.tab("Day"), text="8:00PM", font=("Helvetica", 13))
        self.welcome.grid(row=0, column=8, padx=(0, 12))
        self.welcome = customtkinter.CTkLabel(self.Tabview.tab("Day"), text="9:00PM", font=("Helvetica", 13))
        self.welcome.grid(row=0, column=9, padx=(0, 12))
        self.welcome = customtkinter.CTkLabel(self.Tabview.tab("Day"), text="10:00PM", font=("Helvetica", 13))
        self.welcome.grid(row=0, column=10, padx=(0, 12))
        self.welcome = customtkinter.CTkLabel(self.Tabview.tab("Day"), text="12:00PM", font=("Helvetica", 13))
        self.welcome.grid(row=0, column=12, padx=(0, 12))
        self.welcome = customtkinter.CTkLabel(self.Tabview.tab("Day"), text="12:00PM", font=("Helvetica", 13))
        self.welcome.grid(row=0, column=12, padx=(0, 12))

        self.welcome = customtkinter.CTkLabel(self.Tabview.tab("Day"), text="Mon", font=("Helvetica", 16))
        self.welcome.grid(row=1, column=0, padx=(5, 5), pady=(0, 6), sticky="w")
        self.welcome = customtkinter.CTkLabel(self.Tabview.tab("Day"), text="Tue", font=("Helvetica", 16))
        self.welcome.grid(row=2, column=0, padx=(5, 5), pady=(0, 6), sticky="w")
        self.welcome = customtkinter.CTkLabel(self.Tabview.tab("Day"), text="Wed", font=("Helvetica", 16))
        self.welcome.grid(row=3, column=0, padx=(5, 5), pady=(0, 6), sticky="w")
        self.welcome = customtkinter.CTkLabel(self.Tabview.tab("Day"), text="Thu", font=("Helvetica", 16))
        self.welcome.grid(row=4, column=0, padx=(5, 5), pady=(0, 6),  sticky="w")
        self.welcome = customtkinter.CTkLabel(self.Tabview.tab("Day"), text="Fri", font=("Helvetica", 16))
        self.welcome.grid(row=5, column=0, padx=(5, 5), pady=(0, 6), sticky="w")
        self.welcome = customtkinter.CTkLabel(self.Tabview.tab("Day"), text="Sat", font=("Helvetica", 16))
        self.welcome.grid(row=6, column=0, padx=(5, 5), pady=(0, 6), sticky="w")
        self.welcome = customtkinter.CTkLabel(self.Tabview.tab("Day"), text="Sun", font=("Helvetica", 16))
        self.welcome.grid(row=7, column=0, padx=(5, 5), pady=(0, 6), sticky="w")

        self.welcome = customtkinter.CTkLabel(self.Tabview.tab("Night"), text="1:00PM", font=("Helvetica", 13))
        self.welcome.grid(row=0, column=1, padx=(10, 12))
        self.welcome = customtkinter.CTkLabel(self.Tabview.tab("Night"), text="2:00PM", font=("Helvetica", 13))
        self.welcome.grid(row=0, column=2, padx=(0, 12))
        self.welcome = customtkinter.CTkLabel(self.Tabview.tab("Night"), text="3:00PM", font=("Helvetica", 13))
        self.welcome.grid(row=0, column=3, padx=(0, 12))
        self.welcome = customtkinter.CTkLabel(self.Tabview.tab("Night"), text="4:00PM", font=("Helvetica", 13))
        self.welcome.grid(row=0, column=4, padx=(0, 12))
        self.welcome = customtkinter.CTkLabel(self.Tabview.tab("Night"), text="5:00PM", font=("Helvetica", 13))
        self.welcome.grid(row=0, column=5, padx=(0, 12))
        self.welcome = customtkinter.CTkLabel(self.Tabview.tab("Night"), text="6:00PM", font=("Helvetica", 13))
        self.welcome.grid(row=0, column=6, padx=(0, 12))
        self.welcome = customtkinter.CTkLabel(self.Tabview.tab("Night"), text="7:00PM", font=("Helvetica", 13))
        self.welcome.grid(row=0, column=7, padx=(0, 12))
        self.welcome = customtkinter.CTkLabel(self.Tabview.tab("Night"), text="8:00PM", font=("Helvetica", 13))
        self.welcome.grid(row=0, column=8, padx=(0, 12))
        self.welcome = customtkinter.CTkLabel(self.Tabview.tab("Night"), text="9:00PM", font=("Helvetica", 13))
        self.welcome.grid(row=0, column=9, padx=(0, 12))
        self.welcome = customtkinter.CTkLabel(self.Tabview.tab("Night"), text="10:00PM", font=("Helvetica", 13))
        self.welcome.grid(row=0, column=10, padx=(0, 12))
        self.welcome = customtkinter.CTkLabel(self.Tabview.tab("Night"), text="12:00PM", font=("Helvetica", 13))
        self.welcome.grid(row=0, column=12, padx=(0, 12))
        self.welcome = customtkinter.CTkLabel(self.Tabview.tab("Night"), text="12:00PM", font=("Helvetica", 13))
        self.welcome.grid(row=0, column=12, padx=(0, 12))

        self.welcome = customtkinter.CTkLabel(self.Tabview.tab("Night"), text="Mon", font=("Helvetica", 16))
        self.welcome.grid(row=1, column=0, padx=(5, 5), pady=(0, 6), sticky="w")
        self.welcome = customtkinter.CTkLabel(self.Tabview.tab("Night"), text="Tue", font=("Helvetica", 16))
        self.welcome.grid(row=2, column=0, padx=(5, 5), pady=(0, 6),sticky="w")
        self.welcome = customtkinter.CTkLabel(self.Tabview.tab("Night"), text="Wed", font=("Helvetica", 16))
        self.welcome.grid(row=3, column=0, padx=(5, 5), pady=(0, 6),sticky="w")
        self.welcome = customtkinter.CTkLabel(self.Tabview.tab("Night"), text="Thu", font=("Helvetica", 16))
        self.welcome.grid(row=4, column=0, padx=(5, 5), pady=(0, 6),sticky="w")
        self.welcome = customtkinter.CTkLabel(self.Tabview.tab("Night"), text="Fri", font=("Helvetica", 16))
        self.welcome.grid(row=5, column=0, padx=(5, 5), pady=(0, 6),sticky="w")
        self.welcome = customtkinter.CTkLabel(self.Tabview.tab("Night"), text="Sat", font=("Helvetica", 16))
        self.welcome.grid(row=6, column=0, padx=(5, 5), pady=(0, 6),sticky="w")
        self.welcome = customtkinter.CTkLabel(self.Tabview.tab("Night"), text="Sun", font=("Helvetica", 16))
        self.welcome.grid(row=7, column=0, padx=(5, 5), pady=(0, 6),sticky="w")

        self.welcome = customtkinter.CTkButton(self.Tabview.tab("Night"), text="Sun", width=100, font=("Helvetica", 16))
        self.welcome.grid(row=1, column=5, padx=(5, 5), sticky="w", columnspan=2)
        self.welcome = customtkinter.CTkButton(self.Tabview.tab("Night"), text="Sun", width=100, font=("Helvetica", 16))
        self.welcome.grid(row=2, column=5, padx=(5, 5), sticky="w", columnspan=2)
        self.welcome = customtkinter.CTkButton(self.Tabview.tab("Night"), text="Sun", width=100, font=("Helvetica", 16))
        self.welcome.grid(row=3, column=5, padx=(5, 5), sticky="w", columnspan=2)
        self.welcome = customtkinter.CTkButton(self.Tabview.tab("Night"), text="Sun", width=100, font=("Helvetica", 16))
        self.welcome.grid(row=4, column=5, padx=(5, 5), sticky="w", columnspan=2)
        self.welcome = customtkinter.CTkButton(self.Tabview.tab("Night"), text="Sun", width=100, font=("Helvetica", 16))
        self.welcome.grid(row=5, column=5, padx=(5, 5), sticky="w", columnspan=2)
        self.welcome = customtkinter.CTkButton(self.Tabview.tab("Night"), text="Sun", width=100, font=("Helvetica", 16))
        self.welcome.grid(row=4, column=5, padx=(5, 5), sticky="w", columnspan=2)
        self.welcome = customtkinter.CTkButton(self.Tabview.tab("Night"), text="Sun", width=100, font=("Helvetica", 16))
        self.welcome.grid(row=5, column=5, padx=(5, 5), sticky="w", columnspan=2)
        self.welcome = customtkinter.CTkButton(self.Tabview.tab("Night"), text="Sun", width=100, font=("Helvetica", 16))
        self.welcome.grid(row=6, column=5, padx=(5, 5), sticky="w", columnspan=2)
        self.welcome = customtkinter.CTkButton(self.Tabview.tab("Night"), text="Sun", width=100, font=("Helvetica", 16))
        self.welcome.grid(row=7, column=5, padx=(5, 5), sticky="w", columnspan=2)

    def add(self):
        print("added")

if __name__ == "__main__":
    app = App()
    app.mainloop()
