import customtkinter
# #f130393

app = customtkinter.CTk()
app.title("Sudoko")
app.geometry("425x425")
app.resizable(False, False)
app.grid_columnconfigure(9, weight=1)
app.grid_rowconfigure(9, weight=1)

b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=0, column=0, pady=(1, 1), padx=(2, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=1, column=0, pady=(1, 1), padx=(2, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=2, column=0, pady=(1, 1), padx=(2, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#78c6fa", height=45, width=45)
b1.grid(row=3, column=0, pady=(1, 1), padx=(2, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#78c6fa", height=45, width=45)
b1.grid(row=4, column=0, pady=(1, 1), padx=(2, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#78c6fa", height=45, width=45)
b1.grid(row=5, column=0, pady=(1, 1), padx=(2, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=6, column=0, pady=(1, 1), padx=(2, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=7, column=0, pady=(1, 1), padx=(2, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=8, column=0, pady=(1, 1), padx=(2, 1))


b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=0, column=1, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=1, column=1, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=2, column=1, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#78c6fa", height=45, width=45)
b1.grid(row=3, column=1, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#78c6fa", height=45, width=45)
b1.grid(row=4, column=1, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#78c6fa", height=45, width=45)
b1.grid(row=5, column=1, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=6, column=1, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=7, column=1, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=8, column=1, pady=(1, 1), padx=(1, 1))


b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=0, column=2, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=1, column=2, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=2, column=2, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#78c6fa", height=45, width=45)
b1.grid(row=3, column=2, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#78c6fa", height=45, width=45)
b1.grid(row=4, column=2, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#78c6fa", height=45, width=45)
b1.grid(row=5, column=2, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=6, column=2, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=7, column=2, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=8, column=2, pady=(1, 1), padx=(1, 1))


b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#78c6fa", height=45, width=45)
b1.grid(row=0, column=3, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#78c6fa", height=45, width=45)
b1.grid(row=1, column=3, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#78c6fa", height=45, width=45)
b1.grid(row=2, column=3, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=3, column=3, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=4, column=3, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=5, column=3, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=6, column=3, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=7, column=3, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=8, column=3, pady=(1, 1), padx=(1, 1))


b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#78c6fa", height=45, width=45)
b1.grid(row=0, column=4, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#78c6fa", height=45, width=45)
b1.grid(row=1, column=4, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#78c6fa", height=45, width=45)
b1.grid(row=2, column=4, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=3, column=4, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=4, column=4, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=5, column=4, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=6, column=4, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=7, column=4, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=8, column=4, pady=(1, 1), padx=(1, 1))


b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#78c6fa", height=45, width=45)
b1.grid(row=0, column=5, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#78c6fa", height=45, width=45)
b1.grid(row=1, column=5, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#78c6fa", height=45, width=45)
b1.grid(row=2, column=5, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=3, column=5, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=4, column=5, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=5, column=5, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=6, column=5, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=7, column=5, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=8, column=5, pady=(1, 1), padx=(1, 1))


b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=0, column=6, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=1, column=6, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=2, column=6, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=3, column=6, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=4, column=6, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=5, column=6, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=6, column=6, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=7, column=6, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=8, column=6, pady=(1, 1), padx=(1, 1))


b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=0, column=7, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=1, column=7, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=2, column=7, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=3, column=7, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=4, column=7, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=5, column=7, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=6, column=7, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=7, column=7, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=8, column=7, pady=(1, 1), padx=(1, 1))


b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=0, column=8, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=1, column=8, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=2, column=8, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=3, column=8, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=4, column=8, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=5, column=8, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=6, column=8, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=7, column=8, pady=(1, 1), padx=(1, 1))
b1 = customtkinter.CTkButton(app, text="", font=("Helvetica", 60), fg_color="#ffffff", height=45, width=45)
b1.grid(row=8, column=8, pady=(1, 1), padx=(1, 1))



app.mainloop()
