#Missing data
s=pd.Series(["Anand",np.nan,"Anmol","Albert"])
print(s)
print(s.isnull())
print(s.notnull())
s[3]=None
print(s.isnull())
print(s.dropna())
gas=pd.DataFrame([[1,2,3,6,8,4], [4,NA,5,NA,NA,NA], [NA,NA,NA,2,4]])
print(gas)
print(gas.dropna())
print(gas.dropna(how="all"))
print(gas)
gas[1]=NA
print(gas)
print(gas.dropna(axis=1,how="all"))
print(gas)
print(gas.dropna(thresh=3))
print(gas)
print(gas.fillna(0))
print(gas.fillna({0:15,1:25,2:35}))
print(gas)
print(gas.fillna(0,inplace=True))
print(gas)
gas=pd.DataFrame([[1,2,3],[4,NA,5],
                 [NA,NA,NA]])
print(gas)
print(gas.fillna(method="ffill"))
print(gas.fillna(method="ffill",limit=1))
data=pd.Series([1,0,NA,5])
print(data)
print(data.fillna(data.mean()))
print(gas)
print(gas.fillna(gas.mean()))

